# Generated by Django 4.2.1 on 2023-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="group",
        ),
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Not Informed", "Default"),
                    ("Female", "Female"),
                ],
                default="Not Informed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="group",
            field=models.ManyToManyField(
                null=True, related_name="pets", to="groups.group"
            ),
        ),
    ]
