# Generated by Django 4.2.2 on 2023-06-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_alter_group_created_at"),
        ("pets", "0002_remove_pet_group_alter_pet_sex_pet_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="group",
        ),
        migrations.AddField(
            model_name="pet",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="groups.group",
            ),
        ),
    ]
