# Generated by Django 4.2.2 on 2023-06-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_alter_trait_created_at"),
        ("pets", "0003_remove_pet_group_pet_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
