# Generated by Django 4.2.2 on 2023-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_alter_group_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
